/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "protocol.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>

#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif

void
syscall_prog_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		open_request syscall_open_1_arg;
		openat_request syscall_openat_1_arg;
		close_request syscall_close_1_arg;
		read_request syscall_read_1_arg;
		pread_request syscall_pread_1_arg;
		write_request syscall_write_1_arg;
		pwrite_request syscall_pwrite_1_arg;
		stat_request syscall_stat_1_arg;
		newfstatat_request syscall_newfstatat_1_arg;
		fstat_request syscall_fstat_1_arg;
		fcntl_request syscall_fcntl_1_arg;
		fdatasync_request syscall_fdatasync_1_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case SYSCALL_OPEN:
		_xdr_argument = (xdrproc_t) xdr_open_request;
		_xdr_result = (xdrproc_t) xdr_open_response;
		local = (char *(*)(char *, struct svc_req *)) syscall_open_1_svc;
		break;

	case SYSCALL_OPENAT:
		_xdr_argument = (xdrproc_t) xdr_openat_request;
		_xdr_result = (xdrproc_t) xdr_openat_response;
		local = (char *(*)(char *, struct svc_req *)) syscall_openat_1_svc;
		break;

	case SYSCALL_CLOSE:
		_xdr_argument = (xdrproc_t) xdr_close_request;
		_xdr_result = (xdrproc_t) xdr_close_response;
		local = (char *(*)(char *, struct svc_req *)) syscall_close_1_svc;
		break;

	case SYSCALL_READ:
		_xdr_argument = (xdrproc_t) xdr_read_request;
		_xdr_result = (xdrproc_t) xdr_read_response;
		local = (char *(*)(char *, struct svc_req *)) syscall_read_1_svc;
		break;

	case SYSCALL_PREAD:
		_xdr_argument = (xdrproc_t) xdr_pread_request;
		_xdr_result = (xdrproc_t) xdr_pread_response;
		local = (char *(*)(char *, struct svc_req *)) syscall_pread_1_svc;
		break;

	case SYSCALL_WRITE:
		_xdr_argument = (xdrproc_t) xdr_write_request;
		_xdr_result = (xdrproc_t) xdr_write_response;
		local = (char *(*)(char *, struct svc_req *)) syscall_write_1_svc;
		break;

	case SYSCALL_PWRITE:
		_xdr_argument = (xdrproc_t) xdr_pwrite_request;
		_xdr_result = (xdrproc_t) xdr_pwrite_response;
		local = (char *(*)(char *, struct svc_req *)) syscall_pwrite_1_svc;
		break;

	case SYSCALL_STAT:
		_xdr_argument = (xdrproc_t) xdr_stat_request;
		_xdr_result = (xdrproc_t) xdr_stat_response;
		local = (char *(*)(char *, struct svc_req *)) syscall_stat_1_svc;
		break;

	case SYSCALL_NEWFSTATAT:
		_xdr_argument = (xdrproc_t) xdr_newfstatat_request;
		_xdr_result = (xdrproc_t) xdr_newfstatat_response;
		local = (char *(*)(char *, struct svc_req *)) syscall_newfstatat_1_svc;
		break;

	case SYSCALL_FSTAT:
		_xdr_argument = (xdrproc_t) xdr_fstat_request;
		_xdr_result = (xdrproc_t) xdr_fstat_response;
		local = (char *(*)(char *, struct svc_req *)) syscall_fstat_1_svc;
		break;

	case SYSCALL_FCNTL:
		_xdr_argument = (xdrproc_t) xdr_fcntl_request;
		_xdr_result = (xdrproc_t) xdr_fcntl_response;
		local = (char *(*)(char *, struct svc_req *)) syscall_fcntl_1_svc;
		break;

	case SYSCALL_FDATASYNC:
		_xdr_argument = (xdrproc_t) xdr_fdatasync_request;
		_xdr_result = (xdrproc_t) xdr_fdatasync_response;
		local = (char *(*)(char *, struct svc_req *)) syscall_fdatasync_1_svc;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

#ifndef RPC_SVC_FG
int
main (int argc, char **argv)
{
	register SVCXPRT *transp;

	pmap_unset (SYSCALL_PROG, SYSCALL_VERS);

	transp = svcudp_create(RPC_ANYSOCK);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create udp service.");
		exit(1);
	}
	if (!svc_register(transp, SYSCALL_PROG, SYSCALL_VERS, syscall_prog_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (SYSCALL_PROG, SYSCALL_VERS, udp).");
		exit(1);
	}

	transp = svctcp_create(RPC_ANYSOCK, 0, 0);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create tcp service.");
		exit(1);
	}
	if (!svc_register(transp, SYSCALL_PROG, SYSCALL_VERS, syscall_prog_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (SYSCALL_PROG, SYSCALL_VERS, tcp).");
		exit(1);
	}

	svc_run ();
	fprintf (stderr, "%s", "svc_run returned");
	exit (1);
	/* NOTREACHED */
}
#endif /* RPC_SVC_FG */
