/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _PROTOCOL_H_RPCGEN
#define _PROTOCOL_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

#define MAX_PATH_LEN 4096
#define MAX_BUFFER_SIZE 1048576

struct open_request {
	char *path;
	int flags;
	u_int mode;
};
typedef struct open_request open_request;

struct open_response {
	int fd;
	int result;
	int err;
};
typedef struct open_response open_response;

struct close_request {
	int fd;
};
typedef struct close_request close_request;

struct close_response {
	int result;
	int err;
};
typedef struct close_response close_response;

struct read_request {
	int fd;
	u_int count;
};
typedef struct read_request read_request;

struct read_response {
	struct {
		u_int data_len;
		char *data_val;
	} data;
	int result;
	int err;
};
typedef struct read_response read_response;

struct write_request {
	int fd;
	struct {
		u_int data_len;
		char *data_val;
	} data;
};
typedef struct write_request write_request;

struct write_response {
	int result;
	int err;
};
typedef struct write_response write_response;

#define SYSCALL_PROG 0x20000001
#define SYSCALL_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define SYSCALL_OPEN 1
extern  open_response * syscall_open_1(open_request *, CLIENT *);
extern  open_response * syscall_open_1_svc(open_request *, struct svc_req *);
#define SYSCALL_CLOSE 2
extern  close_response * syscall_close_1(close_request *, CLIENT *);
extern  close_response * syscall_close_1_svc(close_request *, struct svc_req *);
#define SYSCALL_READ 3
extern  read_response * syscall_read_1(read_request *, CLIENT *);
extern  read_response * syscall_read_1_svc(read_request *, struct svc_req *);
#define SYSCALL_WRITE 4
extern  write_response * syscall_write_1(write_request *, CLIENT *);
extern  write_response * syscall_write_1_svc(write_request *, struct svc_req *);
extern int syscall_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define SYSCALL_OPEN 1
extern  open_response * syscall_open_1();
extern  open_response * syscall_open_1_svc();
#define SYSCALL_CLOSE 2
extern  close_response * syscall_close_1();
extern  close_response * syscall_close_1_svc();
#define SYSCALL_READ 3
extern  read_response * syscall_read_1();
extern  read_response * syscall_read_1_svc();
#define SYSCALL_WRITE 4
extern  write_response * syscall_write_1();
extern  write_response * syscall_write_1_svc();
extern int syscall_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_open_request (XDR *, open_request*);
extern  bool_t xdr_open_response (XDR *, open_response*);
extern  bool_t xdr_close_request (XDR *, close_request*);
extern  bool_t xdr_close_response (XDR *, close_response*);
extern  bool_t xdr_read_request (XDR *, read_request*);
extern  bool_t xdr_read_response (XDR *, read_response*);
extern  bool_t xdr_write_request (XDR *, write_request*);
extern  bool_t xdr_write_response (XDR *, write_response*);

#else /* K&R C */
extern bool_t xdr_open_request ();
extern bool_t xdr_open_response ();
extern bool_t xdr_close_request ();
extern bool_t xdr_close_response ();
extern bool_t xdr_read_request ();
extern bool_t xdr_read_response ();
extern bool_t xdr_write_request ();
extern bool_t xdr_write_response ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_PROTOCOL_H_RPCGEN */
