/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _PROTOCOL_H_RPCGEN
#define _PROTOCOL_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

#define MAX_PATH_LEN 4096
#define MAX_BUFFER_SIZE 1048576

struct open_request {
	char *path;
	int flags;
	u_int mode;
};
typedef struct open_request open_request;

struct open_response {
	int fd;
	int result;
	int err;
};
typedef struct open_response open_response;

struct openat_request {
	int dirfd;
	char *path;
	int flags;
	u_int mode;
};
typedef struct openat_request openat_request;

struct openat_response {
	int fd;
	int result;
	int err;
};
typedef struct openat_response openat_response;

struct close_request {
	int fd;
};
typedef struct close_request close_request;

struct close_response {
	int result;
	int err;
};
typedef struct close_response close_response;

struct read_request {
	int fd;
	u_int count;
};
typedef struct read_request read_request;

struct read_response {
	struct {
		u_int data_len;
		char *data_val;
	} data;
	int result;
	int err;
};
typedef struct read_response read_response;

struct pread_request {
	int fd;
	long offset;
	u_int count;
};
typedef struct pread_request pread_request;

struct pread_response {
	struct {
		u_int data_len;
		char *data_val;
	} data;
	int result;
	int err;
};
typedef struct pread_response pread_response;

struct write_request {
	int fd;
	struct {
		u_int data_len;
		char *data_val;
	} data;
};
typedef struct write_request write_request;

struct write_response {
	int result;
	int err;
};
typedef struct write_response write_response;

struct pwrite_request {
	int fd;
	long offset;
	struct {
		u_int data_len;
		char *data_val;
	} data;
};
typedef struct pwrite_request pwrite_request;

struct pwrite_response {
	int result;
	int err;
};
typedef struct pwrite_response pwrite_response;

struct stat_request {
	char *path;
};
typedef struct stat_request stat_request;

struct stat_response {
	int result;
	int err;
	u_long dev;
	u_long ino;
	u_int mode;
	u_int nlink;
	u_int uid;
	u_int gid;
	u_long rdev;
	u_quad_t size;
	u_long blksize;
	u_quad_t blocks;
	u_long atime;
	u_long mtime;
	u_long ctime;
};
typedef struct stat_response stat_response;

struct newfstatat_request {
	int dirfd;
	char *path;
	int flags;
};
typedef struct newfstatat_request newfstatat_request;

struct newfstatat_response {
	int result;
	int err;
	u_long dev;
	u_long ino;
	u_int mode;
	u_int nlink;
	u_int uid;
	u_int gid;
	u_long rdev;
	u_quad_t size;
	u_long blksize;
	u_quad_t blocks;
	u_long atime;
	u_long mtime;
	u_long ctime;
};
typedef struct newfstatat_response newfstatat_response;

struct fstat_request {
	int fd;
};
typedef struct fstat_request fstat_request;

struct fstat_response {
	int result;
	int err;
	u_long dev;
	u_long ino;
	u_int mode;
	u_int nlink;
	u_int uid;
	u_int gid;
	u_long rdev;
	u_quad_t size;
	u_long blksize;
	u_quad_t blocks;
	u_long atime;
	u_long mtime;
	u_long ctime;
};
typedef struct fstat_response fstat_response;

struct flock_data {
	short l_type;
	short l_whence;
	quad_t l_start;
	quad_t l_len;
	int l_pid;
};
typedef struct flock_data flock_data;

enum fcntl_arg_type {
	FCNTL_ARG_NONE = 0,
	FCNTL_ARG_INT = 1,
	FCNTL_ARG_FLOCK = 2,
};
typedef enum fcntl_arg_type fcntl_arg_type;

struct fcntl_arg {
	fcntl_arg_type type;
	union {
		int int_arg;
		flock_data flock_arg;
	} fcntl_arg_u;
};
typedef struct fcntl_arg fcntl_arg;

struct fcntl_request {
	int fd;
	int cmd;
	fcntl_arg arg;
};
typedef struct fcntl_request fcntl_request;

struct fcntl_response {
	int result;
	int err;
	fcntl_arg arg_out;
};
typedef struct fcntl_response fcntl_response;

struct fdatasync_request {
	int fd;
};
typedef struct fdatasync_request fdatasync_request;

struct fdatasync_response {
	int result;
	int err;
};
typedef struct fdatasync_response fdatasync_response;

struct lseek_request {
	int fd;
	quad_t offset;
	int whence;
};
typedef struct lseek_request lseek_request;

struct lseek_response {
	quad_t result;
	int err;
};
typedef struct lseek_response lseek_response;

struct access_request {
	char *path;
	int mode;
};
typedef struct access_request access_request;

struct access_response {
	int result;
	int err;
};
typedef struct access_response access_response;

struct unlink_request {
	char *path;
};
typedef struct unlink_request unlink_request;

struct unlink_response {
	int result;
	int err;
};
typedef struct unlink_response unlink_response;

struct getcwd_request {
	u_int size;
};
typedef struct getcwd_request getcwd_request;

struct getcwd_response {
	char *path;
	int result;
	int err;
};
typedef struct getcwd_response getcwd_response;

struct rlimit_data {
	u_quad_t rlim_cur;
	u_quad_t rlim_max;
};
typedef struct rlimit_data rlimit_data;

struct prlimit64_request {
	int pid;
	int resource;
	bool_t has_new_limit;
	rlimit_data new_limit;
	bool_t request_old_limit;
};
typedef struct prlimit64_request prlimit64_request;

struct prlimit64_response {
	int result;
	int err;
	bool_t has_old_limit;
	rlimit_data old_limit;
};
typedef struct prlimit64_response prlimit64_response;

struct winsize_data {
	u_short ws_row;
	u_short ws_col;
	u_short ws_xpixel;
	u_short ws_ypixel;
};
typedef struct winsize_data winsize_data;

enum ioctl_arg_type {
	IOCTL_ARG_NONE = 0,
	IOCTL_ARG_INT = 1,
	IOCTL_ARG_WINSIZE = 2,
};
typedef enum ioctl_arg_type ioctl_arg_type;

struct ioctl_arg {
	ioctl_arg_type type;
	union {
		int int_arg;
		winsize_data winsize_arg;
	} ioctl_arg_u;
};
typedef struct ioctl_arg ioctl_arg;

struct ioctl_request {
	int fd;
	u_long request;
	ioctl_arg arg_in;
};
typedef struct ioctl_request ioctl_request;

struct ioctl_response {
	int result;
	int err;
	ioctl_arg arg_out;
};
typedef struct ioctl_response ioctl_response;

#define SYSCALL_PROG 0x20000001
#define SYSCALL_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define SYSCALL_OPEN 1
extern  open_response * syscall_open_1(open_request *, CLIENT *);
extern  open_response * syscall_open_1_svc(open_request *, struct svc_req *);
#define SYSCALL_OPENAT 2
extern  openat_response * syscall_openat_1(openat_request *, CLIENT *);
extern  openat_response * syscall_openat_1_svc(openat_request *, struct svc_req *);
#define SYSCALL_CLOSE 3
extern  close_response * syscall_close_1(close_request *, CLIENT *);
extern  close_response * syscall_close_1_svc(close_request *, struct svc_req *);
#define SYSCALL_READ 4
extern  read_response * syscall_read_1(read_request *, CLIENT *);
extern  read_response * syscall_read_1_svc(read_request *, struct svc_req *);
#define SYSCALL_PREAD 5
extern  pread_response * syscall_pread_1(pread_request *, CLIENT *);
extern  pread_response * syscall_pread_1_svc(pread_request *, struct svc_req *);
#define SYSCALL_WRITE 6
extern  write_response * syscall_write_1(write_request *, CLIENT *);
extern  write_response * syscall_write_1_svc(write_request *, struct svc_req *);
#define SYSCALL_PWRITE 7
extern  pwrite_response * syscall_pwrite_1(pwrite_request *, CLIENT *);
extern  pwrite_response * syscall_pwrite_1_svc(pwrite_request *, struct svc_req *);
#define SYSCALL_STAT 8
extern  stat_response * syscall_stat_1(stat_request *, CLIENT *);
extern  stat_response * syscall_stat_1_svc(stat_request *, struct svc_req *);
#define SYSCALL_NEWFSTATAT 9
extern  newfstatat_response * syscall_newfstatat_1(newfstatat_request *, CLIENT *);
extern  newfstatat_response * syscall_newfstatat_1_svc(newfstatat_request *, struct svc_req *);
#define SYSCALL_FSTAT 10
extern  fstat_response * syscall_fstat_1(fstat_request *, CLIENT *);
extern  fstat_response * syscall_fstat_1_svc(fstat_request *, struct svc_req *);
#define SYSCALL_FCNTL 11
extern  fcntl_response * syscall_fcntl_1(fcntl_request *, CLIENT *);
extern  fcntl_response * syscall_fcntl_1_svc(fcntl_request *, struct svc_req *);
#define SYSCALL_FDATASYNC 12
extern  fdatasync_response * syscall_fdatasync_1(fdatasync_request *, CLIENT *);
extern  fdatasync_response * syscall_fdatasync_1_svc(fdatasync_request *, struct svc_req *);
#define SYSCALL_LSEEK 13
extern  lseek_response * syscall_lseek_1(lseek_request *, CLIENT *);
extern  lseek_response * syscall_lseek_1_svc(lseek_request *, struct svc_req *);
#define SYSCALL_ACCESS 14
extern  access_response * syscall_access_1(access_request *, CLIENT *);
extern  access_response * syscall_access_1_svc(access_request *, struct svc_req *);
#define SYSCALL_UNLINK 15
extern  unlink_response * syscall_unlink_1(unlink_request *, CLIENT *);
extern  unlink_response * syscall_unlink_1_svc(unlink_request *, struct svc_req *);
#define SYSCALL_GETCWD 16
extern  getcwd_response * syscall_getcwd_1(getcwd_request *, CLIENT *);
extern  getcwd_response * syscall_getcwd_1_svc(getcwd_request *, struct svc_req *);
#define SYSCALL_PRLIMIT64 17
extern  prlimit64_response * syscall_prlimit64_1(prlimit64_request *, CLIENT *);
extern  prlimit64_response * syscall_prlimit64_1_svc(prlimit64_request *, struct svc_req *);
#define SYSCALL_IOCTL 18
extern  ioctl_response * syscall_ioctl_1(ioctl_request *, CLIENT *);
extern  ioctl_response * syscall_ioctl_1_svc(ioctl_request *, struct svc_req *);
extern int syscall_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define SYSCALL_OPEN 1
extern  open_response * syscall_open_1();
extern  open_response * syscall_open_1_svc();
#define SYSCALL_OPENAT 2
extern  openat_response * syscall_openat_1();
extern  openat_response * syscall_openat_1_svc();
#define SYSCALL_CLOSE 3
extern  close_response * syscall_close_1();
extern  close_response * syscall_close_1_svc();
#define SYSCALL_READ 4
extern  read_response * syscall_read_1();
extern  read_response * syscall_read_1_svc();
#define SYSCALL_PREAD 5
extern  pread_response * syscall_pread_1();
extern  pread_response * syscall_pread_1_svc();
#define SYSCALL_WRITE 6
extern  write_response * syscall_write_1();
extern  write_response * syscall_write_1_svc();
#define SYSCALL_PWRITE 7
extern  pwrite_response * syscall_pwrite_1();
extern  pwrite_response * syscall_pwrite_1_svc();
#define SYSCALL_STAT 8
extern  stat_response * syscall_stat_1();
extern  stat_response * syscall_stat_1_svc();
#define SYSCALL_NEWFSTATAT 9
extern  newfstatat_response * syscall_newfstatat_1();
extern  newfstatat_response * syscall_newfstatat_1_svc();
#define SYSCALL_FSTAT 10
extern  fstat_response * syscall_fstat_1();
extern  fstat_response * syscall_fstat_1_svc();
#define SYSCALL_FCNTL 11
extern  fcntl_response * syscall_fcntl_1();
extern  fcntl_response * syscall_fcntl_1_svc();
#define SYSCALL_FDATASYNC 12
extern  fdatasync_response * syscall_fdatasync_1();
extern  fdatasync_response * syscall_fdatasync_1_svc();
#define SYSCALL_LSEEK 13
extern  lseek_response * syscall_lseek_1();
extern  lseek_response * syscall_lseek_1_svc();
#define SYSCALL_ACCESS 14
extern  access_response * syscall_access_1();
extern  access_response * syscall_access_1_svc();
#define SYSCALL_UNLINK 15
extern  unlink_response * syscall_unlink_1();
extern  unlink_response * syscall_unlink_1_svc();
#define SYSCALL_GETCWD 16
extern  getcwd_response * syscall_getcwd_1();
extern  getcwd_response * syscall_getcwd_1_svc();
#define SYSCALL_PRLIMIT64 17
extern  prlimit64_response * syscall_prlimit64_1();
extern  prlimit64_response * syscall_prlimit64_1_svc();
#define SYSCALL_IOCTL 18
extern  ioctl_response * syscall_ioctl_1();
extern  ioctl_response * syscall_ioctl_1_svc();
extern int syscall_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_open_request (XDR *, open_request*);
extern  bool_t xdr_open_response (XDR *, open_response*);
extern  bool_t xdr_openat_request (XDR *, openat_request*);
extern  bool_t xdr_openat_response (XDR *, openat_response*);
extern  bool_t xdr_close_request (XDR *, close_request*);
extern  bool_t xdr_close_response (XDR *, close_response*);
extern  bool_t xdr_read_request (XDR *, read_request*);
extern  bool_t xdr_read_response (XDR *, read_response*);
extern  bool_t xdr_pread_request (XDR *, pread_request*);
extern  bool_t xdr_pread_response (XDR *, pread_response*);
extern  bool_t xdr_write_request (XDR *, write_request*);
extern  bool_t xdr_write_response (XDR *, write_response*);
extern  bool_t xdr_pwrite_request (XDR *, pwrite_request*);
extern  bool_t xdr_pwrite_response (XDR *, pwrite_response*);
extern  bool_t xdr_stat_request (XDR *, stat_request*);
extern  bool_t xdr_stat_response (XDR *, stat_response*);
extern  bool_t xdr_newfstatat_request (XDR *, newfstatat_request*);
extern  bool_t xdr_newfstatat_response (XDR *, newfstatat_response*);
extern  bool_t xdr_fstat_request (XDR *, fstat_request*);
extern  bool_t xdr_fstat_response (XDR *, fstat_response*);
extern  bool_t xdr_flock_data (XDR *, flock_data*);
extern  bool_t xdr_fcntl_arg_type (XDR *, fcntl_arg_type*);
extern  bool_t xdr_fcntl_arg (XDR *, fcntl_arg*);
extern  bool_t xdr_fcntl_request (XDR *, fcntl_request*);
extern  bool_t xdr_fcntl_response (XDR *, fcntl_response*);
extern  bool_t xdr_fdatasync_request (XDR *, fdatasync_request*);
extern  bool_t xdr_fdatasync_response (XDR *, fdatasync_response*);
extern  bool_t xdr_lseek_request (XDR *, lseek_request*);
extern  bool_t xdr_lseek_response (XDR *, lseek_response*);
extern  bool_t xdr_access_request (XDR *, access_request*);
extern  bool_t xdr_access_response (XDR *, access_response*);
extern  bool_t xdr_unlink_request (XDR *, unlink_request*);
extern  bool_t xdr_unlink_response (XDR *, unlink_response*);
extern  bool_t xdr_getcwd_request (XDR *, getcwd_request*);
extern  bool_t xdr_getcwd_response (XDR *, getcwd_response*);
extern  bool_t xdr_rlimit_data (XDR *, rlimit_data*);
extern  bool_t xdr_prlimit64_request (XDR *, prlimit64_request*);
extern  bool_t xdr_prlimit64_response (XDR *, prlimit64_response*);
extern  bool_t xdr_winsize_data (XDR *, winsize_data*);
extern  bool_t xdr_ioctl_arg_type (XDR *, ioctl_arg_type*);
extern  bool_t xdr_ioctl_arg (XDR *, ioctl_arg*);
extern  bool_t xdr_ioctl_request (XDR *, ioctl_request*);
extern  bool_t xdr_ioctl_response (XDR *, ioctl_response*);

#else /* K&R C */
extern bool_t xdr_open_request ();
extern bool_t xdr_open_response ();
extern bool_t xdr_openat_request ();
extern bool_t xdr_openat_response ();
extern bool_t xdr_close_request ();
extern bool_t xdr_close_response ();
extern bool_t xdr_read_request ();
extern bool_t xdr_read_response ();
extern bool_t xdr_pread_request ();
extern bool_t xdr_pread_response ();
extern bool_t xdr_write_request ();
extern bool_t xdr_write_response ();
extern bool_t xdr_pwrite_request ();
extern bool_t xdr_pwrite_response ();
extern bool_t xdr_stat_request ();
extern bool_t xdr_stat_response ();
extern bool_t xdr_newfstatat_request ();
extern bool_t xdr_newfstatat_response ();
extern bool_t xdr_fstat_request ();
extern bool_t xdr_fstat_response ();
extern bool_t xdr_flock_data ();
extern bool_t xdr_fcntl_arg_type ();
extern bool_t xdr_fcntl_arg ();
extern bool_t xdr_fcntl_request ();
extern bool_t xdr_fcntl_response ();
extern bool_t xdr_fdatasync_request ();
extern bool_t xdr_fdatasync_response ();
extern bool_t xdr_lseek_request ();
extern bool_t xdr_lseek_response ();
extern bool_t xdr_access_request ();
extern bool_t xdr_access_response ();
extern bool_t xdr_unlink_request ();
extern bool_t xdr_unlink_response ();
extern bool_t xdr_getcwd_request ();
extern bool_t xdr_getcwd_response ();
extern bool_t xdr_rlimit_data ();
extern bool_t xdr_prlimit64_request ();
extern bool_t xdr_prlimit64_response ();
extern bool_t xdr_winsize_data ();
extern bool_t xdr_ioctl_arg_type ();
extern bool_t xdr_ioctl_arg ();
extern bool_t xdr_ioctl_request ();
extern bool_t xdr_ioctl_response ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_PROTOCOL_H_RPCGEN */
