/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "protocol.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

open_response *
syscall_open_1(open_request *argp, CLIENT *clnt)
{
	static open_response clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, SYSCALL_OPEN,
		(xdrproc_t) xdr_open_request, (caddr_t) argp,
		(xdrproc_t) xdr_open_response, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

close_response *
syscall_close_1(close_request *argp, CLIENT *clnt)
{
	static close_response clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, SYSCALL_CLOSE,
		(xdrproc_t) xdr_close_request, (caddr_t) argp,
		(xdrproc_t) xdr_close_response, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

read_response *
syscall_read_1(read_request *argp, CLIENT *clnt)
{
	static read_response clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, SYSCALL_READ,
		(xdrproc_t) xdr_read_request, (caddr_t) argp,
		(xdrproc_t) xdr_read_response, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

write_response *
syscall_write_1(write_request *argp, CLIENT *clnt)
{
	static write_response clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, SYSCALL_WRITE,
		(xdrproc_t) xdr_write_request, (caddr_t) argp,
		(xdrproc_t) xdr_write_response, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}
