/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "protocol.h"

bool_t
xdr_open_request (XDR *xdrs, open_request *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->path, MAX_PATH_LEN))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->flags))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->mode))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_open_response (XDR *xdrs, open_response *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->fd))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->result))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->err))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_close_request (XDR *xdrs, close_request *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->fd))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_close_response (XDR *xdrs, close_response *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->result))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->err))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_read_request (XDR *xdrs, read_request *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->fd))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->count))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_read_response (XDR *xdrs, read_response *objp)
{
	register int32_t *buf;

	 if (!xdr_bytes (xdrs, (char **)&objp->data.data_val, (u_int *) &objp->data.data_len, MAX_BUFFER_SIZE))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->result))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->err))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_write_request (XDR *xdrs, write_request *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->fd))
		 return FALSE;
	 if (!xdr_bytes (xdrs, (char **)&objp->data.data_val, (u_int *) &objp->data.data_len, MAX_BUFFER_SIZE))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_write_response (XDR *xdrs, write_response *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->result))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->err))
		 return FALSE;
	return TRUE;
}
